config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  devise_scope :user do
    root 'devise/sessions#new'
  end

  resources :users do
    resources :categories
    resources :conventions
    member do
      get :block
      get :unblock
    end
  end

end

app/models/category.rb
class Category < ActiveRecord::Base


  belongs_to :user
  has_one :convention

  validates :name, presence: true
  TYPE = ["Expense", "Profit"]

  def total(user)
    Convention.where(user_id: user.id, category_id: self.id).pluck(:amount).sum
  end



end

app/models/convention.rb
class Convention < ActiveRecord::Base
  belongs_to :user
  belongs_to :category

  validates :amount, presence:true
  validates :category_id, presence:true
  validates :date, presence:true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :categories
  has_many :conventions

  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

  def percent_json(categories)
    convention_amounts =[]
    categories.where(:category_type => "Expense").each {|cat| exp_amounts << cat.total(self)}
    categories.where(:category_type => "Profit").each {|cat| exp_amounts << cat.total(self)}
    proArr = []
    expArr = []
    categories.each do |cat|
      if cat.category_type == "Expense"
        expArr << {name: cat.name, y:(cat.total(self)/convention_amounts.sum) * 100}
      else
        proArr << {name: cat.name, y:(cat.total(self)/convention_amounts.sum) * 100}
      end
    end
    arr = [expArr, proArr]
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  #before_action :authenticate_user!

  def authenticate_admin
    user_signed_in? and current_user.is_admin?
  end

  private
  def after_sign_out_path_for(resource_or_scope)
    root_path
  end

  def after_sign_in_path_for(resource)
    request.env['omniauth.origin'] || stored_location_for(resource) || users_path
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def new
    @user = User.find(params[:user_id])
    @category = Category.new
  end

  def create
    @user = User.find(params[:user_id])
    @category = @user.categories.create(category_params)
    if @category.errors.present?
      render :template => 'categories/new'
    else
      redirect_to user_path(@user)
    end
  end

  def index
    @user = User.find(params[:user_id])
    @categories = @user.categories
  end

  def show
  end

  private

  def category_params
    params.require(:category).permit!
  end

end

app/controllers/conventions_controller.rb
class ConventionsController < ApplicationController

  before_action :set_select_collection, only: [:new, :create]

  def index
    @user = User.find(params[:user_id])
    @conventions = @user.conventions
  end

  def show
  end

  def new
    @user = User.find(params[:user_id])
    @convention = Convention.new
  end

  def create
    @user = User.find(params[:user_id])
    @convention = @user.conventions.create(convention_params)
    if @convention.errors.present?
      render :template => 'conventions/new'
    else
      redirect_to user_path(@user)
    end
  end

  private

  def convention_params
    params.require(:convention).permit!
  end

  def set_select_collection
    @categories = current_user.categories
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!

  def index
    redirect_to user_path(current_user) if !authenticate_admin
    @users = User.where.not(id: current_user.id)
  end

  def show
    @user = User.find(params[:id])
    @categories = @user.categories
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.name = params[:user][:name]
    @user.avatar = params[:user][:avatar]
    if @user.save
      redirect_to @user
    end
  end

  def destroy

  end

  def block
    @user = User.find(params[:id])
    @user.banned = true
    @user.save
  end

  def unblock
    @user = User.find(params[:id])
    @user.banned = false
    @user.save
  end

  private

  def user_params
    params.require(:users).permit!
  end


end

app/helpers/application_helper.rb
module ApplicationHelper


end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/index.html.haml
.container
  .row
    .col-md-2
      .page-header
        = image_tag @user.avatar.url(:thumb), :class => "img-thumbnail"
        %h1 #{@user.name}
      = link_to "New Categories", new_user_category_path, :class => "btn btn-primary btn-md"
    .col-md-8
      .page-header
      %h2.page-header Categories
      .row.placeholders
        - @categories.each do |category|
          .col-xs-6.col-sm-3.placeholder
            %img.img-responsive{:alt => "Generic placeholder thumbnail", :height => "200", :src => "data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==", :width => "200"}/
            %h4 #{category.name}
            %span.text-muted #{category.category_type}

app/views/categories/new.html.haml
= form_for(@category, :url => user_categories_path(@user), html: {:class =>'form-signin', :multipart => true, :class =>'form-signin'}) do |f|
  - if @category.errors.present?
    - @category.errors.each do |k,val|
      %p #{k} #{val}
  %label Category name
  = f.text_field :name, :class => "form-control", :placeholder => "Category name"
  %label Category Type
  = f.select :category_type, Category::TYPE, {prompt: "Select"}, class: "form-control"
  = f.submit "Save", :class => "btn btn-lg btn-primary btn-block"

app/views/categories/show.html.haml
%h1 Categories#show
%p Find me in app/views/categories/show.html.haml

app/views/conventions/index.html.haml
.container
  .row
    .col-md-2
      .page-header
        = image_tag @user.avatar.url(:thumb), :class => "img-thumbnail"
        %h1 #{@user.name}
        = link_to "New Convention", new_user_convention_path, :class => "btn btn-primary btn-md"
    .col-md-8
      .page-header
      %h2.sub-header Conventions
      .table-responsive
        %table.table.table-striped
          %thead
            %tr
              %th #
              %th Amount
              %th Category
              %th Type
          %tbody
            - @conventions.each do |convention|
              %tr
                %td #{convention.id}
                %td #{convention.amount}
                %td  #{convention.category.name}
                %td  #{convention.category.category_type}

app/views/conventions/new.html.haml
= form_for(@convention, :url => user_conventions_path(@user), html: {:class =>'form-signin', :multipart => true, :class =>'form-signin'}) do |f|
  - if @convention.errors.present?
    - @convention.errors.each do |k,val|
      %p #{k} #{val}
  %label amount
  = f.text_field :amount, :class => "form-control", :placeholder => "Amount"
  %label Date
  = f.date_field :date, class: "form-control"
  %label Category
  = f.select :category_id, options_for_select(@categories.map{|c| [c.name, c.id]}, params[:category_id]),{ :include_blank => "Please select category"}, {:class => "form-control"}
  = f.submit "Save", :class => "btn btn-lg btn-primary btn-block"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Paisadesk
    = stylesheet_link_tag  "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css", integrity:"sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u", crossorigin:"anonymous"
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    - if user_signed_in?
      %nav.navbar.navbar-fixed-top.navbar-inverse
        .container
          .navbar-header
            %button.navbar-toggle.collapsed{"aria-controls" => "navbar", "aria-expanded" => "false", "data-target" => "#navbar", "data-toggle" => "collapse", :type => "button"}
              %span.sr-only Toggle navigation
              %span.icon-bar
              %span.icon-bar
              %span.icon-bar
            %a.navbar-brand{:href => root_path} Paisa Desk
          #navbar.collapse.navbar-collapse
            %ul.nav.navbar-nav
              %li{:class => request.path == user_path(current_user) ? "active" : ""}
                %a{:href => user_path(current_user)} Home
              %li{:class => request.path == user_categories_path(current_user) ? "active" : ""}
                %a{:href => user_categories_path(current_user)} Categories
              %li{:class => request.path == user_conventions_path(current_user) ? "active" : ""}
                %a{:href => user_conventions_path(current_user)} Conventions
              %li
                = link_to "Sign out", destroy_user_session_path, method: :delete
    .div{:class => "container"}
      = yield

    = javascript_include_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js", integrity:"sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa", crossorigin: "anonymous"

app/views/users/_form.html.haml
= form_for(@user, :url => user_path(@user), method: :put, html: {:class =>'form-signin', :multipart => true, :class =>'form-signin'}) do |f|
  %label Name
  = f.text_field :name, :class => "form-control", :placeholder => "Email"
  %label Profile Picture
  = f.file_field :avatar, :class => "form-control"
  = f.submit "Save", :class => "btn btn-lg btn-primary btn-block"

app/views/users/_users.html.haml
%tr
  %td #{user.id}
  %td  #{user.email}
  %td{id: "newAction#{user.id}"}
    = link_to user.banned ? "Unblock" : "Block", user.banned ? unblock_user_path(user) : block_user_path(user),remote: true
  %td
    = link_to "Show", user_path(user)

app/views/users/block.js.erb
$("#newAction<%=@user.id%>").html("<%= escape_javascript link_to(@user.banned ? "Unblock" : "Block", @user.banned ? unblock_user_path(@user) : block_user_path(@user),remote: true) %>");

app/views/users/edit.html.haml
= render "form"

app/views/users/index.html.haml
%h2.sub-header Users
.table-responsive
  %table.table.table-striped
    %thead
      %tr
        %th #
        %th email
        %th Actions
        %th
    %tbody
      - @users.each do |user|
        = render partial: "users", :locals => {:user => user}

app/views/users/show.html.haml
%script{:src => "https://code.highcharts.com/highcharts.js"}
%script{:src => "https://code.highcharts.com/modules/exporting.js"}
.container
  .row
    .col-md-2
      .page-header
        = image_tag @user.avatar.url(:thumb), :class => "img-thumbnail"
        %h1 #{@user.name}
        .row
          #containerExp{:style => "min-width: 210px; height: 180px; max-width: 300px; "}
          #containerPro{:style => "min-width: 210px; height: 180px; max-width: 300px; "}
    .col-md-10
      %h2 Transactions
      - if @categories.present?
        .table-responsive
          %table.table.table-striped
            %thead
              %tr
                %th #
                %th Name
                %th Type
                %th Amount
            %tbody
              - @categories.each do |category|
                %tr
                  %td #{category.id}
                  %td #{category.name}
                  %td #{category.category_type}
                  %td #{category.total(@user)}

:javascript
  Highcharts.chart('containerExp', {
      chart: {
          plotBackgroundColor: null,
          plotBorderWidth: null,
          plotShadow: false,
          type: 'pie'
      },
      title: {
          text: 'Expense Category'
      },
      tooltip: {
          pointFormat: '{series.name}: <b>{point.percentage:.1f}%</b>'
      },
      plotOptions: {
          pie: {
              allowPointSelect: true,
              cursor: 'pointer',
              dataLabels: {
                  enabled: true,
                  format: '<b>{point.name}</b>: {point.percentage:.1f} %',
                  style: {
                      color: (Highcharts.theme && Highcharts.theme.contrastTextColor) || 'black'
                  }
              }
          }
      },
      series: [{
        name: 'Category',
        colorByPoint: true,
        data: #{@user.percent_json(@categories)[0].to_json}
    }]
  });
  Highcharts.chart('containerPro', {
      chart: {
          plotBackgroundColor: null,
          plotBorderWidth: null,
          plotShadow: false,
          type: 'pie'
      },
      title: {
          text: 'Income Category'
      },
      tooltip: {
          pointFormat: '{series.name}: <b>{point.percentage:.1f}%</b>'
      },
      plotOptions: {
          pie: {
              allowPointSelect: true,
              cursor: 'pointer',
              dataLabels: {
                  enabled: true,
                  format: '<b>{point.name}</b>: {point.percentage:.1f} %',
                  style: {
                      color: (Highcharts.theme && Highcharts.theme.contrastTextColor) || 'black'
                  }
              }
          }
      },
      series: [{
        name: 'Category',
        colorByPoint: true,
        data: #{@user.percent_json(@categories)[1].to_json}
    }]
  });

app/views/users/unblock.js.erb
$("#newAction<%=@user.id%>").html("<%= escape_javascript link_to(@user.banned ? "Unblock" : "Block", @user.banned ? unblock_user_path(@user) : block_user_path(@user),remote: true) %>");